# Generated by Django 4.1.7 on 2023-03-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_remove_attachment_owner_attachment_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('Awaiting Review', 'Awaiting Review'), ('In Review', 'In view'), ('Approved', 'Approved')], default='Awaiting Review', max_length=200),
        ),
    ]
