# Generated by Django 4.1.7 on 2023-03-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_project_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
