# Generated by Django 4.1.7 on 2023-03-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_remove_team_workers_worker_team'),
        ('project_manager', '0009_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.team'),
        ),
    ]
