# Generated by Django 4.0 on 2023-03-13 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_profile_company_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, default='', max_length=2000, null=True)),
                ('description', models.TextField()),
                ('company_key', models.CharField(default='', max_length=200)),
                ('logo', models.ImageField(default='', upload_to='logos/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.costumuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.costumuser')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('head', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='manager.worker')),
                ('workers', models.ManyToManyField(to='manager.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('In Qeue', 'In Qeue'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Not Started', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_personal', models.BooleanField(blank=True, default=False, null=True)),
                ('due_in', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.costumuser')),
                ('teams', models.ManyToManyField(blank=True, null=True, to='manager.Team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_dated', to='users.costumuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('In Qeue', 'In Qeue'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Not Started', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('pause_time', models.DurationField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.costumuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated', to='users.costumuser')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='New Activity', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.milestone')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.costumuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
