# Generated by Django 4.0 on 2023-03-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_company_remove_profile_country_and_more'),
        ('manager', '0002_remove_milestone_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-updated'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Companies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, default='No company', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='New Task', max_length=200, verbose_name='Milestone'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.costumuser', verbose_name='Workers'),
        ),
    ]
