# Generated by Django 4.0 on 2023-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_activity_options_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='logos/'),
        ),
    ]
