# Generated by Django 4.0 on 2023-03-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_milestone_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('In Queue', 'In Queue'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='In Queue', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('In Queue', 'In Queue'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='In Queue', max_length=200),
        ),
    ]
