# Generated by Django 4.1.7 on 2023-03-15 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_project_deadline_alter_project_due_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='head',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='manager.worker'),
        ),
    ]
