# Generated by Django 4.1.7 on 2023-03-15 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0012_alter_team_options_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
