# Generated by Django 4.1.7 on 2023-03-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.milestone'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.project'),
        ),
    ]
