# Generated by Django 4.1.7 on 2023-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_task_milestone_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(to='manager.worker'),
        ),
    ]
