# Generated by Django 4.1.7 on 2023-03-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_activity_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='team',
        ),
    ]
