# Generated by Django 4.1.7 on 2023-03-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_remove_attachment_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='workers',
        ),
        migrations.AddField(
            model_name='worker',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.team'),
        ),
    ]
